/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file.h"
#include <memory.h> /* for memset */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = {25, 0};

int *checkfilename_1(char **argp, CLIENT *clnt) {
    static int clnt_res;

    memset((char *)&clnt_res, 0, sizeof(clnt_res));
    if (clnt_call(clnt, CHECKFILENAME, (xdrproc_t)xdr_wrapstring, (caddr_t)argp,
                  (xdrproc_t)xdr_int, (caddr_t)&clnt_res,
                  TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}

myres *fileread_1(char **argp, CLIENT *clnt) {
    static myres clnt_res;

    memset((char *)&clnt_res, 0, sizeof(clnt_res));
    if (clnt_call(clnt, FILEREAD, (xdrproc_t)xdr_wrapstring, (caddr_t)argp,
                  (xdrproc_t)xdr_myres, (caddr_t)&clnt_res,
                  TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}
